services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
  